/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sales.batch.watcher;

public class App {
    public String getGreeting() {
        return "Hello world :D";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
